const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

const userData = [
  {
    fullname: "Alfian Prisma Yopiangga",
    sid_eid: "3120600001",
    email: "yopi@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Bintang Rezeka Ramadani",
    sid_eid: "3120600003",
    email: "zeka@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Muhamad Rifqi Luthfi Ramadhan",
    sid_eid: "3120600004",
    email: "rifqi@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Muqorroba Lada Sattar",
    sid_eid: "3120600005",
    email: "sattar@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Rosalinda Dwi Vicesa",
    sid_eid: "3120600006",
    email: "ocha@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Mu'Adz Fathulloh",
    sid_eid: "3120600007",
    email: "muadz@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Josephine Kristianti Saputra",
    sid_eid: "3120600008",
    email: "josephine@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Muhammad Adryan Prawira Kusuma",
    sid_eid: "3120600010",
    email: "adryan@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Ainul Muhlasin",
    sid_eid: "3120600011",
    email: "ainul@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Raihan Ahnaf Nafisaputra",
    sid_eid: "3120600012",
    email: "rehan@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Faisal Amrullah Pratama",
    sid_eid: "3120600013",
    email: "faisal@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Aqyun Rista Maulidin",
    sid_eid: "3120600014",
    email: "aqyun@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Hafiyyan Dwika Arya",
    sid_eid: "3120600015",
    email: "arya@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Febri Permata Emiliana",
    sid_eid: "3120600016",
    email: "febri@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Ahmed Indarafata Akmal Maulana S.",
    sid_eid: "3120600017",
    email: "andre@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Putri Ayu Nisa Az-Zahra",
    sid_eid: "3120600018",
    email: "puay@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Moh. Zakariya Al Ansori",
    sid_eid: "3120600019",
    email: "alan@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Afnan Amiludin",
    sid_eid: "3120600020",
    email: "afnan@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Muh. Arga Swara Iskandar",
    sid_eid: "3120600021",
    email: "arga@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Setyo Aryo Pangestu",
    sid_eid: "3120600022",
    email: "aryo@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Ade Purnama",
    sid_eid: "3120600023",
    email: "ade@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Muhammad Yus'ad Al Machmudi",
    sid_eid: "3120600025",
    email: "yusad@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Devafilla Rizqy Santosa",
    sid_eid: "3120600026",
    email: "deva@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Ahmad Fasih Nayl Jabaa'Ir",
    sid_eid: "3120600027",
    email: "affa@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Muhammad Nur Faiz",
    sid_eid: "3120600028",
    email: "faiz@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Muhammad Ghifari Ramadhan",
    sid_eid: "3120600029",
    email: "ghifari@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  {
    fullname: "Adek Wisnu Winata",
    sid_eid: "3120600030",
    email: "wisnu@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 1,
  },
  // User ID: 28
  {
    fullname: "Nailussa`ada S.ST., M.Tr.Kom.",
    sid_eid: "199609072020122007",
    email: "nailus@it.lecturer.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 29
  {
    fullname: "Desy Intan Permatasari S.Kom., M.Kom.",
    sid_eid: "198603232015042004",
    email: "desy@it.lecturer.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 30
  {
    fullname: "Umi Sa'adah S.Kom, M.Kom",
    sid_eid: "197404162000032003",
    email: "umi@it.lecturer.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 31
  {
    fullname: "Hero Yudo Martono ST, MT",
    sid_eid: "197811032005011002",
    email: "hero@it.lecturer.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 32
  {
    fullname: "Fadilah Fahrul Hardiansyah S.ST., M. Kom.",
    sid_eid: "198901292019031013",
    email: "fahrul@it.lecturer.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 33
  {
    fullname: "Ahmad Syauqi Ahsan S.Kom., M.T.",
    sid_eid: "197505302003121001",
    email: "syauqi@it.lecturer.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 34
  {
    fullname: "Yuliana Setiowati S.Kom, M.Kom",
    sid_eid: "197807062002122003",
    email: "yuliana@it.lecturer.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 35
  {
    fullname: "Irwan Sumarsono SS., M.Pd.",
    sid_eid: "196912192002121001",
    email: "irwan@it.lecturer.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 36
  {
    fullname: "Aliridho Barakbah S.Kom., Ph.D.",
    sid_eid: "197308162001121001",
    email: "aliridho@it.lecturer.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 37
  {
    fullname: "M. Udin Harun Al Rasyid S.Kom, Ph.D",
    sid_eid: "198108082005011001",
    email: "udinharun@it.lecturer.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  // User ID: 38
  {
    fullname: "Nur Rosyid Mubtadai S.Kom., M.T.",
    sid_eid: "197403182001121005",
    email: "nurrosyid@it.lecturer.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: null,
  },
  //
  {
    fullname: "Santi",
    sid_eid: "3120600031",
    email: "santi@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Gagas Amukti Nandaka",
    sid_eid: "3120600032",
    email: "gagas@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Ricky Ageng Saputra",
    sid_eid: "3120600033",
    email: "ricky@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Muhammad Izzudin Fasya",
    sid_eid: "3120600035",
    email: "fess@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Dania Ayu Juniaputri S.",
    sid_eid: "3120600036",
    email: "dania@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Feby Nihayatus Shibghoh",
    sid_eid: "3120600038",
    email: "feby@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Rafi Akbar Ferdiansyah",
    sid_eid: "3120600040",
    email: "rafi@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Abdul Aziz",
    sid_eid: "3120600041",
    email: "aziz@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Rizki Wahyu N. F.",
    sid_eid: "3120600042",
    email: "rizki@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Muhammad Ramadhan",
    sid_eid: "3120600043",
    email: "ramadhan@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Alfikiyar Tirta Haidar",
    sid_eid: "3120600044",
    email: "haidar@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Hudzaifah Al Labib",
    sid_eid: "3120600045",
    email: "hudzaifah@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Aqilah Akmalia Dewi",
    sid_eid: "3120600046",
    email: "aqilah@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Ikbal Rahmat Taupik",
    sid_eid: "3120600048",
    email: "ikbal@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Hanan Ammar Maulana",
    sid_eid: "3120600049",
    email: "hanan@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Fidisa Anindya Pastika",
    sid_eid: "3120600050",
    email: "fidisa@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Yusril Falih Izzaddien",
    sid_eid: "3120600051",
    email: "yusril@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Sovi Febriani",
    sid_eid: "3120600052",
    email: "sovi@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Mochammad Efendi",
    sid_eid: "3120600053",
    email: "efendi@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Diana Kusuma Dewi",
    sid_eid: "3120600054",
    email: "diana@it.student.pens.ac.id",
    gender: "P",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Habil",
    sid_eid: "3120600055",
    email: "habil@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Tirta Rumy Swandaru",
    sid_eid: "3120600057",
    email: "tirta@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Aladino Zulmar Abadi",
    sid_eid: "3120600058",
    email: "aladino@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Aradhana Luqman W. S.",
    sid_eid: "3120600059",
    email: "aradhana@it.student.pens.ac.id",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 2,
  },
  {
    fullname: "Admin Contendance",
    sid_eid: "01",
    email: "admin@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 2,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 1",
    sid_eid: "001",
    email: "pensasi1@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 2",
    sid_eid: "002",
    email: "pensasi2@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 3",
    sid_eid: "003",
    email: "pensasi3@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 4",
    sid_eid: "004",
    email: "pensasi4@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 5",
    sid_eid: "005",
    email: "pensasi5@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 6",
    sid_eid: "006",
    email: "pensasi6@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 7",
    sid_eid: "007",
    email: "pensasi7@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 8",
    sid_eid: "008",
    email: "pensasi8@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 9",
    sid_eid: "009",
    email: "pensasi9@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
  {
    fullname: "Tester PENSASI 10",
    sid_eid: "0010",
    email: "pensasi10@contendance.studio",
    gender: "L",
    password: bcrypt.hashSync("password"),
    role_id: 1,
    study_group_id: 3,
  },
];

async function main() {
  console.log(`Start seeding user ...`);
  for (const u of userData) {
    const user = await prisma.users.create({
      data: u,
    });
    console.log(`Created user with id: ${user.sid_eid}`);
  }
  console.log("Seeding user finished");
}

module.exports = main;
