name: Contendance Backend - CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
          
      - run: "Create init env"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET_TOKEN: ${{ secrets.JWT_SECRET_TOKEN }}
          PORT: 5000
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DH_USERNAME }}/contendance-backend:latest
        
        
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker rm contendance-backend
            docker image rm contendance-backend:latest
            docker pull ${{ secrets.DH_USERNAME }}/contendance-backend:latest
            docker run -d -p 5000:5000 contendance-backend:latest
